# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

def pods
pod 'ETImageBrowser', path: '../'
end

target 'Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo
  pods

end
